name: repo_scraper
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-190.0.dev <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  yaml: ^3.1.1
  encrypt: ^5.0.1
  mysql_client: ^0.0.19
  intl: ^0.17.0
  uuid: ^3.0.6

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
