CREATE DATABASE db;

USE db;

CREATE TABLE posts(
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description MEDIUMTEXT NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    imageUrl VARCHAR(255),
    tags VARCHAR(255) NOT NULL,
    video VARCHAR(255),
    gitLink VARCHAR(255),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE UNIQUE INDEX title ON posts (title);
CREATE INDEX tags ON posts (tags);

CREATE USER 'user'@'%' IDENTIFIED BY 'pass';

GRANT ALL ON *.* TO 'user'@'%';

FLUSH PRIVILEGES;